"""Generate docs/checks-reference.md from the checks' docstrings.

The table and sections come from the docstring of each class registered in
`quacklint.checks.builtin`; the example SQL is obtained by calling `to_sql()`
on real instances, so the document cannot drift out of sync with the code.

Usage:
    uv run python scripts/gen_checks_reference.py          # (re)writes the file
    uv run python scripts/gen_checks_reference.py --check  # fails if out of date
"""

from __future__ import annotations

import inspect
import sys
from datetime import timedelta
from pathlib import Path

from quacklint.checks.base import Check, registered_checks
from quacklint.checks.builtin import (
    AcceptedValuesCheck,
    CustomSqlCheck,
    FreshnessCheck,
    NotNullCheck,
    RangeCheck,
    RegexMatchCheck,
    RowCountCheck,
    UniqueCheck,
)

DOC_PATH = Path(__file__).resolve().parents[1] / "docs" / "checks-reference.md"

# Example instances to show the actual SQL each check generates.
_EXAMPLES: dict[str, Check] = {
    "not_null": NotNullCheck("trips", ["trip_id", "pickup_ts"]),
    "unique": UniqueCheck("trips", ["trip_id"]),
    "accepted_values": AcceptedValuesCheck("trips", "payment_type", ["card", "cash"]),
    "range": RangeCheck("trips", "fare", 0, 1000),
    "regex_match": RegexMatchCheck("trips", "trip_id", "t-[0-9]{3}"),
    "freshness": FreshnessCheck("trips", "pickup_ts", timedelta(hours=24)),
    "row_count": RowCountCheck("trips", 1, 100000),
    "custom_sql": CustomSqlCheck(
        "trips", "no_negative_duration", "SELECT * FROM trips WHERE dropoff_ts < pickup_ts"
    ),
}

_HEADER = """\
<!-- Generated by scripts/gen_checks_reference.py from the docstrings in
     src/quacklint/checks/builtin.py. DO NOT edit by hand:
     uv run python scripts/gen_checks_reference.py -->

# Checks reference

Each check compiles to a DuckDB SQL query whose rows are the rule
**violations**: 0 rows = the check passes. You can inspect the SQL of your
suite with `quacklint run suite.yaml --explain`. Referencing a nonexistent
column is a configuration error (exit 2), not a check failure. The full YAML
format syntax is in the contract: [spec.yaml.md](spec.yaml.md).
"""


def _docstring(check_cls: type[Check]) -> str:
    doc = inspect.getdoc(check_cls)
    if not doc:
        raise SystemExit(f"check '{check_cls.__name__}' has no docstring")
    return doc


def _summary(check_cls: type[Check]) -> str:
    return _docstring(check_cls).splitlines()[0].rstrip(".")


def generate() -> str:
    checks = registered_checks()  # registration order = builtin.py order
    lines: list[str] = [_HEADER]

    lines.append("| Check | Rule |")
    lines.append("| ----- | ---- |")
    for name, check_cls in checks.items():
        lines.append(f"| [`{name}`](#{name}) | {_summary(check_cls)}. |")
    lines.append("")

    for name, check_cls in checks.items():
        lines.append(f"## {name}")
        lines.append("")
        lines.append(_docstring(check_cls))
        lines.append("")
        lines.append("Generated SQL (example):")
        lines.append("")
        lines.append("```sql")
        lines.append(_EXAMPLES[name].to_sql("trips"))
        lines.append("```")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    content = generate()
    if "--check" in argv:
        current = DOC_PATH.read_text(encoding="utf-8") if DOC_PATH.exists() else ""
        if current != content:
            print(
                f"{DOC_PATH} is out of date. "
                "Regenerate it with: uv run python scripts/gen_checks_reference.py"
            )
            return 1
        print(f"{DOC_PATH} is up to date.")
        return 0
    DOC_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
